#url: http://ottumwa1stchurch.github.io
url: http://ottumwa1stchurch.com/
#baseurl: /agency-jekyll-theme/
baseurl:
# Site settings:
title: First Church of the Open Bible
title2: First Church <span style="font-size:.65em">of the</span> <span style="font-size:.85em">Open Bible</span>
#title: Open Bible

email: joshmccall221@gmail.com

description: "Welcome to Ottumwa 1st Church of the Open Bible!"

# Color settings (hex-codes without the leading hash-tag)
color:
  # primary: E84F00  ### 1 burnt orange
  primary: 52b5c6c2  ### easter blue
  #primary: 749FD0  ### sarah suggestion
  #primary: 2E67A6  ### blue
  #primary:115198    ### dark blue
  # secondary: ff971c  ### 1 light orange
  secondary: 52c67ac2  ### easter green
  # secondary: e5cc00  ### easter orange
  # BB0808 ### light maroon
  #secondary: FFB70F   ### lighter yellow
  #secondary: 033cfe
  secondary-dark: 333

graphics:
  background-image: inside-church-may-2019-crop.jpg



people:
- name: Mark & Jen Hornback
  pic: markhornbackandfam
  position: Lead Pastor
  social:

other-people:
- name: Katie Keith
  pic: KatieKeith
  position: Director - Soul Sisters
  social:

- name: Travis & Sarah Peel
  pic: travisandsarah
  position: Revolution Youth Ministries
  social:

- name: Amanda VanZante
  pic: AmandaVanZante
  position: Kids Club
  social:

- name: Cooper Smith & Rachel Warrick
  pic: cooper-rachel
  position: Leaders - Rooted Young Adult Ministries
  social:

- name: Andrew and Katie Huff
  pic: andrew-katie
  position: Directors - Cross Connections Small Group Ministries
  social:

- name: Ben & LaTisha Boeck
  pic: ben-latisha
  position: Directors - Welcome Posse
  social:


social:

  - title: facebook
    url: https://www.facebook.com/FirstChurchOfTheOpenBibleOfOttumwa

# Postal address (add as many lines as necessary)
address:
  - line: 1932 Albia Rd
  - line: Ottumwa, IA 52501

# Build settings
markdown: kramdown
permalink: pretty

collections:
  events:
    output: true
    permalink: /events/:title:output_ext
