#url: http://ottumwa1stchurch.github.io
url: http://ottumwa1stchurch.com/
#baseurl: /agency-jekyll-theme/
baseurl:
# Site settings:
title: First Church of the Open Bible
title2: First Church <span style="font-size:.65em">of the</span> <span style="font-size:.85em">Open Bible</span>
#title: Open Bible

email: joshmccall221@gmail.com

description: "Welcome to Ottumwa 1st Church of the Open Bible!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: E84F00  ### burnt orange
  #primary: 749FD0  ### sarah suggestion
  #primary: 2E67A6  ### blue
  #primary:115198    ### dark blue
  secondary: ff971c  ### light orange
  # BB0808 ### light maroon
  #secondary: FFB70F   ### lighter yellow
  #secondary: 033cfe
  secondary-dark: 333

graphics:
  background-image: front-church-sm.jpg



people:
- name: Mark & Jen Hornback
  pic: markhornbackandfam
  position: Lead Pastor
  social:

other-people:
- name: Katie Keith
  pic: KatieKeith
  position: Director - Soul Sisters
  social:

- name: Travis & Sarah Peel
  pic: travisandsarah
  position: Leaders - Kids Club!
  social:

- name: Kurtis Rupe
  pic: KurtisRupe
  position: Director - Revolution Youth Ministries
  social:

social:

  - title: facebook
    url: https://www.facebook.com/FirstChurchOfTheOpenBibleOfOttumwa

# Postal address (add as many lines as necessary)
address:
  - line: 1932 Albia Rd
  - line: Ottumwa, IA 52501

# Build settings
markdown: kramdown
permalink: pretty

collections:
  events:
    output: true
    permalink: /events/:title:output_ext
